CREATE DATABASE defrost_app;

USE defrost_app;

CREATE TABLE defrost_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phone_number VARCHAR(32) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
